const errorCodes = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  NOT_CREATED_USER: 'NOT_CREATED_USER',
  NOT_DELETED_USER: 'NOT_DELETED_USER',
  NOT_UPDATED_USER: 'NOT_UPDATED_USER',
  USER_ID_NOT_FOUND: 'USER_ID_NOT_FOUND',
  USER_NOT_RETRIEVED: 'USER_NOT_RETRIEVED',
};

module.exports = errorCodes;
